version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: debts-manager
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d
  redis:
    image: redislabs/rejson
    hostname: redis
    command: redis-server --appendonly yes --loadmodule /usr/lib/redis/modules/rejson.so
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
volumes:
  postgres-data: {}
  redis-data: {}
